"""Models package for Job Agent."""

from job_agent.models.database import (
    SearchProfile,
    PlatformAccount,
    Job,
    Application,
    AuditLog,
    EmailThread,
    EmailDraft,
    AgentRun,
    PlatformInterruption,
    MasterDocument,
    DocumentVersion,
    CandidateProfile,
    ConnectionStatus,
    AutomationMode,
    ApplicationStatus,
    AuditAction,
    EmailThreadStatus,
    EmailDraftStatus,
    RunStatus,
    DocumentType,
    DocumentFormat,
    FieldCategory,
)

__all__ = [
    "SearchProfile",
    "PlatformAccount",
    "Job",
    "Application",
    "AuditLog",
    "EmailThread",
    "EmailDraft",
    "AgentRun",
    "PlatformInterruption",
    "MasterDocument",
    "DocumentVersion",
    "CandidateProfile",
    "ConnectionStatus",
    "AutomationMode",
    "ApplicationStatus",
    "AuditAction",
    "EmailThreadStatus",
    "EmailDraftStatus",
    "RunStatus",
    "DocumentType",
    "DocumentFormat",
    "FieldCategory",
]
